Logofix
CodingPridePlatform/codingpride pull request #39
Opened 2021-02-02 07:59 UTC by JAYBLA

2021-02-02 18:42 UTC, Jonas1015 requested changes
Sijaelewa hapa mkuu. What was is it that you were actually doing?

2021-02-02 18:48 UTC, JAYBLA commented
Nimebadili logo,nimeweka footer iwe fixed bottom na pia nmeweka css
specific to login forms

On Tue, Feb 2, 2021, 9:43 PM Jonas <notifications@github.com> wrote:

> *@Jonas1015* requested changes on this pull request.
>
> Sijaelewa hapa mkuu. What was is it that you were actually doing?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/CodingPridePlatform/codingpride/pull/39#pullrequestreview-581660771>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APOWJIFW32J5P4E2F543XATS5BBTVANCNFSM4W6FKSCQ>
> .
>

2021-02-02 18:56 UTC, Jonas1015 commented
Sawa sawa mkuu

2021-02-02 19:07 UTC, ZendaInnocent approved these changes

2021-02-03 20:10 UTC, devmedtz approved these changes

2021-02-03 20:10 UTC, merged