add installation guide
CodingPridePlatform/codingpride pull request #8
Opened 2021-01-21 05:31 UTC by ZendaInnocent

2021-01-21 18:16 UTC, devmedtz approved these changes

2021-01-22 08:24 UTC, JAYBLA requested changes
The Database name is not Postgres, I think crearly shoud be named as PostgreSql Database

2021-01-22 18:06 UTC, Jonas1015 approved these changes
Time to merge

2021-01-22 19:51 UTC, CodingPridePlatform approved these changes

2021-01-23 08:27 UTC, merged